repo-update 2025-01-28 04:49

diff --git a/bin/futf b/bin/futf
--- a/bin/futf
+++ b/bin/futf
@@ -8,141 +8,226 @@ Usage:
 
 Convert file to utf-8 encoded unix text. By default: replace tabs with
 spaces (except in makefiles), remove trailing whitespaces, remove
-leading/trailing blank lines, and backup original file.
+leading and trailing blank lines, and backup original file.
 
 Options:
-  -t, --tabwidth <num>  number of spaces per tab
-  -L, --lines           keep leading and trailing blank lines
-  -O, --overwrite       overwrite input file
-  -S, --spaces          keep trailing whitespaces
-  -T, --tabs            keep tabs
-  -H, -h, --help        print help and exit
+  -t, --tab <num>   spaces per tab (default: 4)
+  -A, --ascii       convert to pure ascii
+  -B, --keepblanks  keep leading and trailing blank lines
+  -N, --nobackup    don't backup original file
+  -S, --keepspaces  keep trailing whitespaces
+  -T, --keeptabs    keep tabs
+  -M, --nocolor     disable colored output
+  -Q, --quiet       print nothing to stdout
+  -V, --verbose     print more verbose information
+  -H, -h, --help    print help and exit
 
-REQUIREMENTS
-    cmp, dos2unix, expand, iconv, uchardet
+Environment:
+  NO_COLOR      disable colored output
+  QUIET         run silently
+  VERBOSE       run verbosely
 HELPDOC
 exit "${1:-0}" ;}
 [[ $1 =~ ^(-H|-h|--help)$ ]] && print_help
 
-# TODO: take stdin?
-# TODO: -A --ascii option
-# TODO: do without dos2unix, expand, ...?
+## settings ::
+debug=0 nocolor=0 quiet=0 verbose=0
+ascii=0 keepblanks=0 keepspaces=0 keeptabs=0 nobackup=0
+overwrite=0 tab=4
+ext_org='_org'
 
-# options:
-ext_original='_org'
+## internal functions/variables ::
+readonly -a args=("$@"); args_options=() args_positionals=()
+readonly -a deps=(cmp dos2unix expand iconv uchardet)
+readonly -a opts=(-t: --tab: -A --ascii -B --keepblanks
+    -N --nobackup -S --keepspaces -T --keeptabs
+    -M --nocolor -Q --quiet -V --verbose -H -h --help)
+files_tmp=() enc= ext= file= file_tmp= file_tmp1= name=
 
-## internal control::
-args=("$@")
-a=0
-arg="${args[a]}"
-flg_keeplines=false
-flg_keepspaces=false
-flg_keeptabs=false
-flg_overwrite=false
-opt_tabwidth=4
-reqs=(cmp dos2unix expand iconv uchardet)
+# colors:
+black=$'\e[38;5;0m' blue=$'\e[38;5;12m' cyan=$'\e[38;5;14m'
+green=$'\e[38;5;10m' grey=$'\e[38;5;8m' magenta=$'\e[38;5;13m'
+orange=$'\e[38;5;3m' red=$'\e[38;5;9m' white=$'\e[38;5;15m'
+yellow=$'\e[38;5;11m' bold=$'\e[1m' off=$'\e[0m'
+clear_colors() {
+    export NO_COLOR=true; nocolor=1
+    unset black blue cyan green grey magenta orange red white yellow bold off
+}
 
-## functions ::
-msg() { printf "\e[1;38;5;12m=> \e[0;38;5;15m$1\e[0m\n" "${@:2}" ;}
-msg_error() { printf "\e[1;38;5;9mE: \e[0;38;5;15m$1\e[0m\n" "${@:2}" >&2 ;}
-msg_warn() { printf "\e[1;38;5;11mW: \e[0;38;5;15m$1\e[0m\n" "${@:2}" >&2 ;}
+# messages:
+msg() { printf "$bold$blue=> $off$white%s$off\n" "$*" ;}
+msg2() { printf "$bold$blue > $off$white%s$off\n" "$*" ;}
+msg_error() { printf "$bold${red}E: $off$white%s$off\n" "$*" >&2 ;}
+msg_good() { printf "$bold$green=> $off$white%s$off\n" "$*" ;}
+msg_plain() { printf "$off$white  %s$off\n" "$*" ;}
+msg_warn() { printf "$bold${yellow}W: $off$white%s$off\n" "$*" >&2 ;}
+msg_cmd() {
+    local _printf='printf'; [[ -f /usr/bin/printf ]] && _printf='/usr/bin/printf'
+    [[ $EUID -eq 0 ]] && printf "$bold$red:#" || printf "$bold$blue:$"
+    printf "$off$white"; "$_printf" ' %q' "$@"; printf "$off\n"
+}
 
-## main() ::
-while [ -n "$arg" ]; do case "$arg" in
-    -t|--tabwidth)
-        [ $# -le $((a+1)) ] && msg_error "arg required: $arg" && exit 2
-        opt_tabwidth="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -L|--lines)
-        flg_keeplines=true; arg="${args[((++a))]}" ;;
-    -O|--overwrite)
-        flg_overwrite=true; arg="${args[((++a))]}" ;;
-    -S|--spaces)
-        flg_keepspaces=true; arg="${args[((++a))]}" ;;
-    -T|--tabs)
-        flg_keeptabs=true; arg="${args[((++a))]}" ;;
-    -H|--help)
-        print_help; exit 0 ;;
-    -[LOSTH]*)
-        if [[ ! "${arg:2:1}" =~ [LOSTHt] ]]; then
-            msg_error "unknown option: ${arg:2:1}"; exit 2
-        fi
-        args[a--]="-${arg:2}"; arg="${arg:0:2}" ;;
-    -[t]*)
-        args[a]="${arg:2}"; arg="${arg:0:2}"; ((a--)) ;;
-    --)
-        ((a++)); break ;;
-    *)
-        break ;;
-esac; done
-args=("${args[@]:a}")
+# utils:
+check_deps() {
+    local deps_err=()
+    for dep in "${deps[@]}"; do is_cmd "$dep" || deps_e+=("$dep"); done
+    [[ ${#deps_err} -gt 0 ]] && msg_error "missing deps: ${deps_err[*]}"
+    return ${#deps_err[@]}
+}
+is_cmd() { command -v "$1" &>/dev/null ;}
 
-for req in "${reqs[@]}"; do if ! command -v "$req" &>/dev/null; then
-    msg_error 'missing requirement: %s' "$req"
-    exit 7
-fi; done
+parse_args() {
+    local a=0 opt= sflgs= sopts= arg="${args[0]}"
+    local -a lflgs=() lopts=()
+    args_options=() args_positionals=()
+    bad_opt() { msg_error "unrecognized option: -${arg:2:1}" ;}
+    bad_optarg() { msg_error "option requires an argument: $arg" ;}
+    bad_flg() { msg_error "option does not take argument: ${arg%%=*}" ;}
+    for opt in "${opts[@]}"; do case "$opt" in
+        -?) sflgs="$sflgs${opt:1}" ;;
+        -?:) sopts="$sopts${opt:1:1}" ;;
+        *:) lopts+=("${opt:0:-1}") ;;
+        *) lflgs+=("$opt") ;;
+    esac; done
+    while [[ -n $arg ]]; do case "$arg" in
+        --) ((a++)); break ;;
+        -[$sflgs]) args_options+=("$arg") ;;
+        -[$sflgs]*) [[ ! $sflgs$sopts =~ ${arg:2:1} ]] && { bad_opt; return 3 ;}
+            args_options+=("${arg:0:2}") arg="-${arg:2}"; continue ;;
+        -[$sopts]) [[ $((${#args[@]}-a)) -le 1 ]] && { bad_optarg; return 3 ;}
+            args_options+=("$arg" "${args[((++a))]}") ;;
+        -[$sopts]*) args_options+=("${arg:0:2}" "${arg:2}") ;;
+        *=*) [[ " ${lflgs[*]} " =~ " ${arg%%=*} " ]] && { bad_flg; return 3 ;}
+            [[ " ${lopts[*]} " =~ " ${arg%%=*} " ]] || break
+            args_options+=("${arg%%=*}" "${arg#*=}") ;;
+        *) if [[ " ${lflgs[*]} " =~ " $arg " ]]; then
+                args_options+=("$arg")
+            elif [[ " ${lopts[*]} " =~ " $arg " ]]; then
+                [[ ${#args[@]} -le $((a+1)) ]] && { bad_optarg; return 3 ;}
+                args_options+=("$arg" "${args[((++a))]}")
+            else break; fi ;;
+    esac; arg="${args[((++a))]}"; done
+    args_positionals=("${args[@]:a}")
+}
 
-if ! [[ "$opt_tabwidth" =~ ^[1-9][0-9]*$ ]]; then
-    msg_error "bad width: $opt_tabwidth"
-    exit 2
-fi
+# error, exit, trap:
+error() { msg_error "$*"; exit 3 ;}
+trap_exit() { rm -f "${files_tmp[@]}"; ((debug)) && msg_warn '[exit]' ;}
+trap_int() { printf '\n'; ((debug)) && msg_warn '[sigint]'; exit 99 ;}
 
-for arg in "${args[@]}"; do
-    if [ -d "$arg" ]; then
-        msg_warn 'directory: %s' "$arg"
-        continue
-    elif [ ! -f "$arg" ]; then
-        msg_warn 'no such file: %s' "$arg"
-        continue
-    fi
+## main ::
+trap trap_int INT
+trap trap_exit EXIT
+
+# set from env:
+[[ -n $DEBUG ]] && debug=1
+[[ -n $NO_COLOR || ! -t 1 || ! -t 2 ]] && clear_colors
+[[ -n $QUIET ]] && quiet=1 verbose=0
+[[ -n $VERBOSE ]] && quiet=0 verbose=1
+
+# parse args:
+parse_args || exit
+set -- "${args_options[@]}"
+while [[ -n $1 ]]; do case "$1" in
+    -t|--tab) shift; tab="$1" ;;
+    -A|--ascii) ascii=1 ;;
+    -B|--keepblanks) keepblanks=1 ;;
+    -N|--nobackup) nobackup=1 ;;
+    -S|--keepspaces) keepspaces=1 ;;
+    -T|--keeptabs) keeptabs=1 ;;
+    -Q|--quiet) quiet=1 verbose=0 ;;
+    -V|--verbose) quiet=0 verbose=1 ;;
+    -M|--nocolor) clear_colors ;;
+    -h|-H|--help) print_help ;;
+esac; shift; done
+
+# check for errors:
+check_deps || exit
+[[ $tab =~ ^[1-9][0-9]*$ ]] || error "invalid tab width: $tab"
+
+for file in "${args_positionals[@]}"; do
+    [[ -d $file ]] && { msg_warn "directory: $file"; continue ;}
+    [[ -f $file ]] || { msg_warn "not found: $file"; continue ;}
+
+    # create and track tmp files:
+    file_tmp="$(mktemp --tmpdir tmp.XXX)"
+    file_tmp1="$(mktemp --tmpdir tmp.XXX)"
+    files_tmp+=("$file_tmp" "$file_tmp1")
+    ((verbose)) && msg_cmd cp "$file" "$file_tmp"
+    cp "$file" "$file_tmp"
 
     # convert to unix (remove any \r, remove BOM, ensure EOL on last line):
-    tmp="$(mktemp)"
-    if ! dos2unix -e -q -r -n "$arg" "$tmp"; then
-        msg_warn 'dos2unix: %s' "$arg"
-        rm "$tmp"
-        continue
+    ((verbose)) && msg_cmd dos2unix -e -q -r -n "$file_tmp" "$file_tmp1"
+    if dos2unix -e -q -r -n "$file_tmp" "$file_tmp1" &>/dev/null; then
+        file_tmp="$file_tmp1"
+    else
+        msg_warn "dos2unix error: $file"
     fi
 
     # ensure utf-8 encoding:
-    enc="$(uchardet "$tmp")"
-    if [ "$enc" != 'UTF-8' ]; then
-        tmp1="$(mktemp)"
-        if ! iconv -f "$enc" -t UTF-8 -o "$tmp1" "$tmp" &>/dev/null; then
-            msg_warn 'iconv: %s' "$arg"
-            rm "$tmp" "$tmp1"
-            continue
+    ((verbose)) && msg_cmd uchardet "$file_tmp"
+    if enc="$(uchardet "$file_tmp" 2>/dev/null)"; then
+        ((verbose)) && msg2 "$enc"
+        if [[ $enc != UTF-8 && $enc != ASCII ]]; then
+            file_tmp1="$(mktemp --tmpdir tmp.XXX)"; files_tmp+=("$file_tmp1")
+            cmd_iconv=(iconv -f "$enc" -t UTF-8 -o "$file_tmp1" "$file_tmp")
+            [[ $enc == unknown ]] && cmd_iconv=(iconv -t UTF-8 -o "$file_tmp1" "$file_tmp")
+            ((verbose)) && msg_cmd "${cmd_iconv[@]}"
+            if "${cmd_iconv[@]}" &>/dev/null; then
+                file_tmp="$file_tmp1"
+            else
+                msg_error "iconv error: $file"
+            fi
         fi
-        mv "$tmp1" "$tmp"
+    else
+        msg_error "uchardet error: $file"
     fi
 
     # replace tabs with spaces:
-    if [ "$flg_keeptabs" = 'false' ] && [ "${arg,,}" != 'makefile' ]; then
-        tmp1="$(mktemp)"
-        if ! expand -t "$opt_tabwidth" "$tmp" > "$tmp1"; then
-            msg_warn 'expand: %s' "$arg"
-            rm "$tmp" "$tmp1"
-            continue
-        fi
-        mv "$tmp1" "$tmp"
-    fi
+    if ! ((keeptabs)) && [[ ${arg,,} != makefile ]]; then
+        file_tmp1="$(mktemp --tmpdir tmp.XXX)"; files_tmp+=("$file_tmp1")
+        ((verbose)) && msg_cmd expand -t "$tab" "$file_tmp" '>' "$file_tmp1"
+        if expand -t "$tab" "$file_tmp" > "$file_tmp1"; then
+            file_tmp="$file_tmp1"
+        else
+            msg_n 'expand error: %s' "$arg"
+    fi; fi
+
+    # convert to ascii:
+    if ((ascii)); then
+        file_tmp1="$(mktemp --tmpdir tmp.XXX)"; files_tmp+=("$file_tmp1")
+        ((verbose)) && msg_cmd iconv -f utf-8 -t ascii//TRANSLIT -o "$file_tmp1" "$file_tmp"
+        if iconv -f utf-8 -t ascii//TRANSLIT -o "$file_tmp1" "$file_tmp"; then
+            file_tmp="$file_tmp1"
+        else
+            msg_n 'iconv error: %s' "$arg"
+    fi; fi
 
     # strip trailing whitespaces:
-    if [ "$flg_keepspaces" = 'false' ]; then
-        sed -i 's/\s\+$//' "$tmp"
+    if ! ((keepspaces)); then
+        ((verbose)) && msg_cmd sed -i 's/\s\+$//' "$file_tmp"
+        sed -i 's/\s\+$//' "$file_tmp"
     fi
 
     # remove leading/trailing blank lines:
-    if [ "$flg_keeplines" = 'false' ]; then
-        sed -i -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba' "$tmp"
+    if ! ((keepblanks)); then
+        ((verbose)) && msg_cmd sed -i -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba' "$file_tmp"
+        sed -i -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba' "$file_tmp"
     fi
 
     # cp/mv new file:
-    if ! cmp -s "$tmp" "$arg"; then
-        msg '%s' "$arg"
-        [ "$flg_overwrite" != 'true' ] && cp "$arg" "$arg${ext_original}"
-        cp "$tmp" "$arg"
+    if ! cmp -s "$file" "$file_tmp"; then
+        if ! ((nobackup)); then
+            name="$file" ext=
+            [[ $file =~ ^(.+)(\..*) ]] && ext="${BASH_REMATCH[2]}" name="${BASH_REMATCH[1]}"
+            cp "$file" "$name${ext_org}$ext"
+        fi
+        ((verbose)) && msg_cmd cp "$file_tmp" "$file"
+        cp "$file_tmp" "$file"
+        ((quiet)) || msg "$file ${green}[updated]"
+    elif ((verbose)); then
+        msg "$file ${blue}[unchanged]"
     fi
-    rm "$tmp"
 done
 
 # vim:ft=bash
