repo-update 2024-06-30 21:42

diff --git a/bin/img-caption b/bin/img-caption
--- a/bin/img-caption
+++ b/bin/img-caption
@@ -140,6 +140,7 @@ msg_to() { msg "$1$(printf ' \e[1;38;5;12m-> \e[0;38;5;15m%s\e[0m' "${@:2}")" ;}
 is_img() { [ -f "$1" ] && identify "$1" &>/dev/null ;}
 
 cmd_exec() { [ "$flg_verbose" = true ] && msg_cmd "$@"; "$@" ;}
+
 cmd_exec_magick() {
     cmd_exec magick -gravity "$cap_align" -background '#00000000' \
         -font "$opt_font" -fill "$opt_fc" -strokewidth $stroke_w -stroke "$opt_sc" \
@@ -179,9 +180,9 @@ while [ -n "$arg" ]; do case "$arg" in
         [ $# -le $((a+1)) ] && error "arg required: $arg" && exit 3
         opt_tmp="${args[((++a))]}"; arg="${args[((++a))]}"
         case "$opt_tmp" in
-            c|center) cmds+=(opt_align=center) ;;
-            r|right) cmds+=(opt_align=west) ;;
-            l|left) cmds+=(opt_align=east) ;;
+            c|center) cmds+=(opt_align=c) ;;
+            r|right) cmds+=(opt_align=w) ;;
+            l|left) cmds+=(opt_align=e) ;;
             *) error "invalid alignment: $opt_tmp" ;;
         esac ;;
     -b|--bg|--background)
@@ -274,7 +275,7 @@ args=("${args[@]:a}")
 
 # check image:
 [ ${#args[@]} -eq 0 ] && error 'no input image'
-is_img "${args[0]}" || error "invalid image: $img"
+is_img "${args[0]}" || error "invalid image: ${args[0]}"
 
 # set image, image_width, image_height:
 img="${args[0]}"
@@ -283,13 +284,16 @@ img_h="${img_w#* }"
 img_w="${img_w% *}"
 
 # set caption padding:
-cap_pad=$((img_w/100))
+cap_pad=$((img_w/250))
 
 dir_tmp="$(mktemp -d)"
 [ "$flg_keep" = false ] && trap "rm -r $dir_tmp" EXIT
 
+# execute commands:
 for cmd in "${cmds[@]}"; do
-    if [ "$cmd" = mk_cap ]; then
+    if [[ "$cmd" =~ ^(flg|opt)_.+=.*$ ]]; then
+        declare "$cmd"
+    elif [ "$cmd" = mk_cap ]; then
         ((c++))
         cap_file=$(printf '%s/cap_%02d.png' "$dir_tmp" $c)
         cap_w=$((img_w*opt_width/100-cap_pad*2))
@@ -398,7 +402,6 @@ for cmd in "${cmds[@]}"; do
 
         # opt_bg:
         if [ $opt_bg -ne 0 ]; then
-            cap_pad=$((img_w/250))
             cap_w=$((cap_w+cap_pad*2))
             cap_h=$((cap_h+cap_pad*2))
             cap_box="roundrectangle 0,0,$cap_w,$cap_h,$((cap_pad*2)),$((cap_pad*2))"
@@ -468,8 +471,6 @@ for cmd in "${cmds[@]}"; do
         cap_h_last=$cap_h
         cap_align_last_last=$cap_align
 
-    else
-        eval "$(printf ' %q' "$cmd")"
     fi
 done
 
diff --git a/bin/img-sharpen b/bin/img-sharpen
--- a/bin/img-sharpen
+++ b/bin/img-sharpen
@@ -16,6 +16,9 @@ OPTIONS
     -J, --jpg
         Output to jpg file.
 
+    -N, --no
+        Skip if output file already exists without prompting.
+
     -P, --png
         Output to png file.
 
@@ -24,6 +27,12 @@ OPTIONS
 
     -V, --verbose
         Print executed commands.
+
+    -Y, --yes
+        Overwrite files without prompting.
+
+    -o, --output FILE
+        Set output filename.
 
     -q, --quality LEVEL
         Set jpg quality level (0-100, default=92).
@@ -38,7 +47,6 @@ HELPDOC
 
 # control:
 ext=
-flg_success=false
 img=
 img_out=
 reqs=(identify magick)
@@ -47,14 +55,17 @@ reqs=(identify magick)
 a=0 arg="$1" args=("$@")
 flg_quiet=false
 flg_verbose=false
+flg_yes=false
+flg_no=false
 opt_level=1
 opt_qual=92
 opt_type=
+opt_out=
 
 ## functions ::
 error() { msg_error "$@"; exit 5 ;}
 msg() { printf "\e[1;38;5;12m=> \e[0;38;5;15m$1\e[0m\n" "${@:2}" ;}
-msg_cmd() { printf "\e[1;38;5;12m $ \e[0;38;5;15m$1\e[0m\n" "${@:2}" ;}
+msg_cmd() { printf '\e[1;38;5;12m $\e[0;38;5;15m'; printf ' %q' "$@"; printf '\n' ;}
 msg_error() { printf "\e[1;38;5;9mE: \e[0;38;5;15m$1\e[0m\n" "${@:2}" >&2 ;}
 msg_to() { msg "$1$(printf ' \e[1;38;5;12m-> \e[0;38;5;15m%s\e[0m' "${@:2}")" ;}
 is_img() { [ -f "$1" ] && identify "$1" &>/dev/null ;}
@@ -63,19 +74,24 @@ is_img() { [ -f "$1" ] && identify "$1" &>/dev/null ;}
 while [ -n "$arg" ]; do case "$arg" in
     -H|--help) print_help; exit 0 ;;
     -J|--jpg) opt_type='jpg'; arg="${args[((++a))]}" ;;
+    -N|--no) flg_no=true; flg_yes=false; arg="${args[((++a))]}" ;;
     -P|--png) opt_type='png'; arg="${args[((++a))]}" ;;
     -Q|--quiet) flg_quiet=true; flag_verbose=false; arg="${args[((++a))]}" ;;
     -V|--verbose) flg_quiet=false; flg_verbose=true; arg="${args[((++a))]}" ;;
+    -Y|--yes) flg_no=false; flg_yes=true; arg="${args[((++a))]}" ;;
+    -o|--output)
+        [ $# -le $((a+1)) ] && error "arg required: $arg" && exit 3
+        opt_out="${args[((++a))]}"; arg="${args[((++a))]}" ;;
     -q|--quality)
         [ $# -le $((a+1)) ] && error "arg required: $arg" && exit 3
         opt_qual="${args[((++a))]}"; arg="${args[((++a))]}" ;;
     -s|--sigma|--sharpen)
         [ $# -le $((a+1)) ] && error "arg required: $arg" && exit 3
         opt_level="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -[HJPQV]*)
-        [[ ! "${arg:2:1}" =~ [HJPQVqs] ]] && error "unknown option: ${arg:2:1}"
+    -[HJNPQVY]*)
+        [[ ! "${arg:2:1}" =~ [HJNPQVYoqs] ]] && error "unknown option: ${arg:2:1}"
         args[a--]="-${arg:2}"; arg="${arg:0:2}" ;;
-    -[qs]*) args[a]="${arg:2}"; arg="${arg:0:2}"; ((a--)) ;;
+    -[oqs]*) args[a]="${arg:2}"; arg="${arg:0:2}"; ((a--)) ;;
     --) ((a++)); break ;;
     *) break ;;
 esac; done
@@ -85,37 +101,53 @@ for req in "${reqs[@]}"; do if ! command -v "$req" &>/dev/null; then
     error "missing requirement: $req"
 fi; done
 
-# set radius and sigma sharpen value:
+# set sharpen level, jpg quality:
 [[ ! "$opt_level" =~ .*x.* ]] && opt_level="0x$opt_level"
 
 # check options:
-[[ ! "$opt_level" =~ ^[0-9]+x[0-9](\.[0-9]*)?$ ]] && error "invalid sharpen level: $opt_level"
-[[ ! "$opt_qual" =~ ^([1-9]|[1-9][0-9]|100)$ ]] && error "invalid jpg quality: $opt_qual"
+[[ ! "$opt_level" =~ ^[0-9]+\.?[0-9]*x[0-9]+\.?[0-9]*$ ]] && error "invalid sharpen level: $opt_level"
+[[ ! "$opt_qual" =~ ^(0|[1-9][0-9]?|100)$ ]] && error "invalid jpg quality: $opt_qual"
+[ ${#args[@]} -gt 1 ] && [ -n "$opt_out" ] && error "cannot set output with multiple inputs"
 
 for img in "${args[@]}"; do
     ! is_img "$img" && msg_error "invalid image: $img" && continue
 
     # set output image name and extension:
-    if [ -n "$opt_type" ]; then
-        ext="$opt_type"
-    else
-        ext="${img##*.}"
+    if [ -n "$opt_out" ]; then
+        img_out="$opt_out"
+        ext="${img_out##*.}"
         ext="${ext,,}"
-        [ -z "$ext" ] || [ "$ext" = 'jpeg' ] && ext='jpg'
+    else
+        if [ -n "$opt_type" ]; then
+            ext="$opt_type"
+        else
+            ext="${img##*.}"
+            ext="${ext,,}"
+            [ -z "$ext" ] || [ "$ext" = 'jpeg' ] && ext='jpg'
+        fi
+        img_out="${img%.*}_s$opt_level.$ext"
     fi
-    img_out="${img%.*}_s${opt_level//./-}.${ext}"
+
+    # prompt/exit:
+    if [ -e "$img_out" ]; then
+        if [ "$flg_no" = true ]; then
+            continue
+        elif [ "$flg_yes" = true ]; then
+            :
+        else
+            read -erp $'\e[1;38;5;10m'': '$'\e[0;38;5;15m''overwrite '"$img_out"'? [y/N] '$'\e[0m' ans
+            [ -z "$ans" ] && continue
+            [ "${ans,,}" != y ] && [ "${ans,,}" != yes ] && continue
+        fi
+    fi
 
     # sharpen image:
-    flg_success=false
+    cmd=(magick "$img" -sharpen "$opt_level")
+    [ "$ext" = 'jpg' ] && [ "$opt_qual" -ne 0 ] && cmd+=(-quality "$opt_qual")
+    cmd+=("$img_out")
     [ "$flg_quiet" = 'false' ] && msg_to "$img" "$img_out"
-    if [ "$ext" = 'jpg' ]; then
-        [ "$flg_verbose" = true ] && msg_cmd "magick $img -sharpen $opt_level -quality $opt_qual $img_out"
-        magick "$img" -sharpen "$opt_level" -quality "$opt_qual" "$img_out" &>/dev/null && flg_success=true
-    else
-        [ "$flg_verbose" = true ] && msg_cmd "magick $img -sharpen $opt_level $img_out"
-        magick "$img" -sharpen "$opt_level" "$img_out" &>/dev/null && flg_success=true
-    fi
-    [ "$flg_quiet" = 'false' ] && [ "$flg_success" = 'false' ] &&  msg_error "magick error: $img"
+    [ "$flg_verbose" = true ] && msg_cmd "${cmd[@]}"
+    ! "${cmd[@]}" &>/dev/null && flg_quiet=false && msg_error "magick error: $img"
 done
 
 # vim:ft=bash
