repo-update 2025-01-12 22:12

diff --git a/bin/img-upscale b/bin/img-upscale
--- a/bin/img-upscale
+++ b/bin/img-upscale
@@ -1,153 +1,277 @@
 #!/bin/bash
 ## img-upscale ::
 
+[[ $0 != "${BASH_SOURCE[0]}" ]] && return 0
 print_help() { cat <<'HELPDOC'
-NAME
-    img-upscale - upscale images
+Usage:
+  img-upscale [option...] <image...>
 
-SYNOPSIS
-    img-upscale [OPTION...] <IMAGE...>
+Upscale images with waifu2x.
 
-DESCRIPTION
-    Upscale images with waifu2x.
+Options:
+  -m, --model <model>   upscale model (anime/cunet/photo, default: cunet)
+  -n, --noise <level>   denoise level (-1/0/1/2/3, default=0)
+  -o, --output <format> output filename format (default: %p_u%s%m%n.%t)
+  -q, --quality <level> jpg quality level (0-100, default=92)
+  -s, --scale <level>   upscale level (1/2/4/8/16/32, default=2)
+  -J, --jpg             output to jpg file
+  -P, --png             output to png file
+  -Q, --quiet           print nothing to stdout
+  -V, --verbose         print more verbose information
+  -H, -h, --help        print help and exit
 
-OPTIONS
-    -J, --jpg
-        Output to jpg file.
+Format:
+  %%    a literal %
+  %d    directory containing input image
+  %F    input image filename
+  %f    input image filename without extension
+  %M    upscale model
+  %m    first letter of upscale model
+  %n    denoise level
+  %P    input image directory+filename
+  %p    input image directory+filename without extension
+  %s    upscale level
+  %t    output image type
 
-    -P, --png
-        Output to png file.
-
-    -Q, --quiet
-        Suppress all messages.
-
-    -V, --verbose
-        Print executed commands.
-
-    -m, --model MODEL
-        Set upscale model (anime/cunet/photo, default=cunet).
-
-    -n, --noise LEVEL
-        Set denoise level (-1/0/1/2/3, default=0).
-
-    -q, --quality LEVEL
-        Set jpg quality level (0-100, default=92).
-
-    -s, --scale LEVEL
-        Set upscale level (1/2/4/8/16/32, default=2).
-
-    -H, --help
-        Print help.
+Environment:
+  NO_COLOR      disable colored output
+  QUIET         run silently
+  VERBOSE       run verbosely
 HELPDOC
-}; [ "$0" != "$BASH_SOURCE" ] && { print_help; return 1 ;}
+exit ;}
+[[ $1 =~ ^(-H|-h|--help)$ ]] && print_help
 
-## control ::
+## settings ::
+debug=0; no_color=0; quiet=0; verbose=0
 bin_waifu2x='waifu2x-ncnn-vulkan'
-deps=(identify magick "$bin_waifu2x")
-flg_success=false
 path_models="/usr/share/$bin_waifu2x"
+model=cunet; noise=0; quality=92; scale=2
+output='%p_u%s%m%n.%t'
 
-# args:
-a=0 arg="$1" args=("$@")
-flg_quiet=false
-flg_verbose=false
-opt_model=cunet
-opt_noise=0
-opt_qual=92
-opt_scale=2
-opt_type=
+## internal functions/variables ::
+readonly -a args=("$@")
+readonly -a deps=("$bin_waifu2x" identify magick)
+readonly -a opts=(
+    -m: --model: -n: --noise: -o: --output: -q: --quality: -s: --scale:
+    -J --jpg -P --png -H -h --help -M --nocolor -Q --quiet -V --verbose)
+readonly script="$(realpath "$BASH_SOURCE")"
+args_options=() args_positionals=()
+dir_model=
+img_out=
+imgs=()
+imgs_error=()
+text_sub=
+type=jpg
 
-## functions ::
-error() { msg_error "$@"; exit 5 ;}
+# colors:
+black=$'\e[38;5;0m'; blue=$'\e[38;5;12m'; cyan=$'\e[38;5;14m'
+green=$'\e[38;5;10m'; grey=$'\e[38;5;8m'; magenta=$'\e[38;5;13m'
+orange=$'\e[38;5;3m'; red=$'\e[38;5;9m' white=$'\e[38;5;15m'
+yellow=$'\e[38;5;11m'; bold=$'\e[1m'; off=$'\e[0m'
+clear_colors() {
+    nocolor=1
+    export NO_COLOR=true
+    unset black blue cyan green grey magenta orange red white yellow bold off
+}
+
+# messages:
+msg() { printf "$bold$blue=> $off$white%s$off\n" "$*" ;}
+msg2() { printf "$bold$blue > $off$white%s$off\n" "$*" ;}
+msg_debug() { printf "$yellow$BASH_LINENO$bold: $off$white%s$off\n" "$*" >&2 ;}
+msg_error() { printf "$bold${red}E: $off$white%s$off\n" "$*" >&2 ;}
+msg_good() { printf "$bold$green=> $off$white%s$off\n" "$*" ;}
+msg_plain() { printf "$off$white  %s$$off\n" "$*" ;}
+msg_warn() { printf "$bold${yellow}W: $off$white%s$off\n" "$*" >&2 ;}
+msg_cmd() {
+    local _printf='printf'; [[ -f /usr/bin/printf ]] && _printf='/usr/bin/printf'
+    [[ $EUID -eq 0 ]] && printf "$bold$red #" || printf "$bold$blue $"
+    printf "$off$white"; "$_printf" ' %q' "$@"; printf "$off\n"
+}
+
+# errors:
+error_exit() { msg_error "$*"; exit 3 ;}
+
+# tests:
+check_deps() {
+    local deps_e=()
+    for dep in "${deps[@]}"; do is_cmd "$dep" || deps_e+=("$dep"); done
+    [[ ${#deps_e} -gt 0 ]] && msg_error "missing deps: ${deps_e[*]}"
+    return ${#deps_e[@]}
+}
 is_cmd() { command -v "$1" &>/dev/null ;}
-is_img() { [ -f "$1" ] && identify "$1" &>/dev/null ;}
-msg() { printf "\e[1;38;5;12m=> \e[0;38;5;15m$1\e[0m\n" "${@:2}" ;}
-msg_cmd() { printf "\e[1;38;5;12m $ \e[0;38;5;15m$1\e[0m\n" "${@:2}" ;}
-msg_error() { printf "\e[1;38;5;9mE: \e[0;38;5;15m$1\e[0m\n" "${@:2}" >&2 ;}
-msg_to() { msg "$1$(printf ' \e[1;38;5;12m-> \e[0;38;5;15m%s\e[0m' "${@:2}")" ;}
-msg_warn() { printf '\e[1;38;5;11mW: \e[0;38;5;15m%s\e[0m\n' "$*" >&2 ;}
+is_img() { [[ -f $1 ]] && identify "$1" &>/dev/null ;}
+is_port() { [[ $1 =~ ^[1-9][0-9]*$ && $1 -lt 65536 ]] ;}
+
+# parsers:
+parse_args() {
+    local a=0 opt= sflgs= sopts= arg="${args[0]}"
+    local -a lflgs=() lopts=()
+    args_options=() args_positionals=()
+    bad_opt() { msg_error "unrecognized option: -${arg:2:1}" ;}
+    bad_optarg() { msg_error "option requires an argument: $arg" ;}
+    bad_flg() { msg_error "option does not take argument: ${arg%%=*}" ;}
+    for opt in "${opts[@]}"; do case "$opt" in
+        -?) sflgs="$sflgs${opt:1}" ;;
+        -?:) sopts="$sopts${opt:1:1}" ;;
+        *:) lopts+=("${opt:0:-1}") ;;
+        *) lflgs+=("$opt") ;;
+    esac; done
+    while [[ -n $arg ]]; do case "$arg" in
+        --) ((a++)); break ;;
+        -[$sflgs]) args_options+=("$arg") ;;
+        -[$sflgs]*) [[ ! $sflgs$sopts =~ ${arg:2:1} ]] && { bad_opt; return 3 ;}
+            args_options+=("${arg:0:2}"); arg="-${arg:2}"; continue ;;
+        -[$sopts]) [[ $((${#args[@]}-a)) -le 1 ]] && { bad_optarg; return 3 ;}
+            args_options+=("$arg" "${args[((++a))]}") ;;
+        -[$sopts]*) args_options+=("${arg:0:2}" "${arg:2}") ;;
+        *=*) [[ " ${lflgs[*]} " =~ " ${arg%%=*} " ]] && { bad_flg; return 3 ;}
+            [[ " ${lopts[*]} " =~ " ${arg%%=*} " ]] || break
+            args_options+=("${arg%%=*}" "${arg#*=}") ;;
+        *) if [[ " ${lflgs[*]} " =~ " $arg " ]]; then
+                args_options+=("$arg")
+            elif [[ " ${lopts[*]} " =~ " $arg " ]]; then
+                [[ ${#args[@]} -le $((a+1)) ]] && { bad_optarg; return 3 ;}
+                args_options+=("$arg" "${args[((++a))]}")
+            else break; fi ;;
+    esac; arg="${args[((++a))]}"; done
+    args_positionals=("${args[@]:a}")
+}
+
+sub_text() {
+    local i=0 found=0
+    text_sub=
+    for sub in "${subs[@]}"; do
+        [[ ${sub:1:1} == : ]] || { msg_error "invalid sub: $sub"; return 3 ;}
+    done
+    while [[ $i -lt ${#text} ]]; do
+        repl="${text:i:1}"
+        if [[ ${text:i:1} == % ]]; then
+            ((i++))
+            if [[ ${text:i:1} == % ]]; then
+                repl='%'
+            else
+                found=0; for sub in "${subs[@]}"; do
+                    if [[ ${text:i:1} == ${sub:0:1} ]]; then
+                        repl="${sub:2}"; ((found++))
+                fi; done
+                if ! ((found)); then
+                    msg_error "invalid format character: ${text:i:1}"
+                    return 3
+                fi
+                ((found)) || { msg_error "invalid format: ${text:i:1}"; return 3 ;}
+        fi; fi
+        text_sub+="$repl"; ((i++))
+    done
+}
+
+# cleanup, exit:
+trap_exit() { rm -f "$img_tmp" ;}
+trap_int() { printf '\n'; msg_error 'keyboard interrupt'; exit 99 ;}
 
 ## main ::
-trap exit INT
-while [ -n "$arg" ]; do case "$arg" in
-    -H|--help) print_help; exit 0 ;;
-    -J|--jpg) opt_type=jpg; arg="${args[((++a))]}" ;;
-    -P|--png) opt_type=png; arg="${args[((++a))]}" ;;
-    -Q|--quiet) flg_quiet=true; flag_verbose=false; arg="${args[((++a))]}" ;;
-    -V|--verbose) flg_quiet=false; flg_verbose=true; arg="${args[((++a))]}" ;;
-    -m|--model)
-        [ $# -le $((a+1)) ] && error "arg required: $arg"
-        opt_model="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -n|--noise)
-        [ $# -le $((a+1)) ] && error "arg required: $arg"
-        opt_noise="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -q|--quality)
-        [ $# -le $((a+1)) ] && error "arg required: $arg"
-        opt_qual="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -s|--scale)
-        [ $# -le $((a+1)) ] && error "arg required: $arg"
-        opt_scale="${args[((++a))]}"; arg="${args[((++a))]}" ;;
-    -[HJPQV]*)
-        [[ ! "${arg:2:1}" =~ [HJPQVmnqs] ]] && error "unknown option: ${arg:2:1}"
-        args[a--]="-${arg:2}"; arg="${arg:0:2}" ;;
-    -[mnqs]*) args[a]="${arg:2}"; arg="${arg:0:2}"; ((a--)) ;;
-    --) ((a++)); break ;;
-    *) break ;;
-esac; done
-args=("${args[@]:a}")
+trap trap_int INT
+trap trap_exit EXIT
 
-# check dependencies:
-for dep in "${deps[@]}"; do is_cmd "$dep" || error "missing dep: $dep"; done
+# set from env:
+[[ -n $DEBUG ]] && debug=1
+[[ -n $NO_COLOR || ! -t 1 || ! -t 2 ]] && { no_color=1; clear_colors ;}
+[[ -n $QUIET ]] && { quiet=1; verbose=0 ;}
+[[ -n $VERBOSE ]] && { quiet=0; verbose=1 ;}
 
-# set upscale model:
-opt_model="${opt_model,,}"
-if [ "$opt_model" = 'anime' ]; then
-    model="$path_models/models-upconv_7_anime_style_art_rgb"
-elif [ "$opt_model" = 'cunet' ]; then
-    model="$path_models/models-cunet"
-elif [ "$opt_model" = 'photo' ]; then
-    model="$path_models/models-upconv_7_photo"
-else
-    error "invalid model: $opt_model"
-fi
+# parse args:
+parse_args || exit
+set -- "${args_options[@]}"
+while [[ -n $1 ]]; do case "$1" in
+    -m|--model) shift; model="$1" ;;
+    -n|--noise) shift; noise="$1" ;;
+    -o|--output) shift; output="$1" ;;
+    -q|--quality) shift; quality="$1" ;;
+    -s|--scale) shift; scale="$1" ;;
+    -J|--jpg) type='jpg' ;;
+    -P|--png) type='png' ;;
+    -Q|--quiet) quiet=1; verbose=0 ;;
+    -V|--verbose) quiet=0; verbose=1 ;;
+    -M|--nocolor) no_color=1; clear_colors ;;
+    -h|-H|--help) print_help ;;
+esac; shift; done
 
-# check options:
-[ ! -d "$model" ] && error "invalid model dir: $model"
-[[ ! "$opt_noise" =~ ^(-1|0|1|2|3)$ ]] && error "invalid denoise level: $opt_noise"
-[[ ! "$opt_scale" =~ ^(1|2|4|16|32)$ ]] && error "invalid upscale level: $opt_scale"
-[[ ! "$opt_qual" =~ ^([1-9]|[1-9][0-9]|100)$ ]] && error "invalid jpg quality: $opt_qual"
+# check for errors:
+check_deps || exit
+[[ $model =~ ^(anime|cunet|photo)$ ]] || error "invalid model: $model"
+[[ $noise =~ ^(-1|0|1|2|3)$ ]] || error "invalid denoise level: $noise"
+[[ $quality =~ ^([1-9]|[1-9][0-9]|100)$ ]] || error "invalid jpg quality: $quality"
+[[ $scale =~ ^(1|2|4|16|32)$ ]] || error "invalid upscale level: $scale"
 
-trap 'rm -f "$img_tmp"' EXIT
-for img in "${args[@]}"; do
-    ! is_img "$img" && msg_error "invalid image: $img" && continue
+# set model directory:
+case "${model,,}" in
+    anime) dir_model="$path_models/models-upconv_7_anime_style_art_rgb" ;;
+    cunet) dir_model="$path_models/models-cunet" ;;
+    photo) dir_model="$path_models/models-upconv_7_photo" ;;
+esac
 
-    # set output image name and extension:
-    if [ -n "$opt_type" ]; then
-        ext="$opt_type"
+# check positional args:
+for arg in "${args_positionals[@]}"; do
+    if is_img "$arg"; then
+        imgs+=("$arg")
     else
-        ext="${img##*.}"
-        ext="${ext,,}"
-        [ -z "$ext" ] || [ "$ext" = 'jpeg' ] && ext='jpg'
+        imgs_error+=("$arg")
     fi
-    img_out="${img%.*}_u${opt_scale}n${opt_noise}${opt_model:0:1}.${ext}"
+done
+[[ -n $imgs_error ]] && msg_warn "not images: ${imgs_error[*]}"
+
+for img in "${imgs[@]}"; do
+    # set format variables:
+    dir=''; file="$img"; file_base="$img"; path="$img"
+    if [[ $img =~ ^(.*/)(.*)$ ]]; then
+        dir="${BASH_REMATCH[1]}"
+        file="${BASH_REMATCH[2]}"
+        file_base="${BASH_REMATCH[2]}"
+    fi
+    if [[ $file =~ ^([^.].*)\.(.*)$ ]]; then
+        file_base="${BASH_REMATCH[1]}"
+
+        # TODO: tmp type for each img
+        if [[ -z $type ]]; then
+            type="${BASH_REMATCH[2]}"; type="${type,,}"
+            [[ $type == jpeg ]] && type=jpg
+        fi
+
+    fi
+    path_base="$dir${file_base}"
+    [[ -z $type ]] && type=jpg
+
+    # format output filename:
+    text="$output"
+    subs=("d:$dir" "F:$file" "f:${file_base}" "M:$model" "m:${model:0:1}"
+        "n:$noise" "P:${path_base}" "p:$path" "s:$scale" "t:$type")
+    sub_text || exit
+    img_out="$text_sub"
+    ((debug)) && { msg_debug "$img $yellow->$white $img_out"; continue ;}
 
     # upscale image:
     img_tmp="$(mktemp --tmpdir XXX.png)"
-    flg_success=false
-    [ "$flg_quiet" = 'false' ] && msg_to "$img" "$img_out"
-    [ "$flg_verbose" = true ] && msg_cmd "waifu2x-ncnn-vulkan -m $model -s $opt_scale -n $opt_noise -i $img -o ${img_tmp}"
-    waifu2x-ncnn-vulkan -m "$model" -s "$opt_scale" -n "$opt_noise" -i "$img" -o "${img_tmp}" &>/dev/null && flg_success=true
-    [ "$flg_quiet" = 'false' ] && [ "$flg_success" = 'false' ] &&  msg_error "$img" && continue
-
-    # convert to jpg:
-    if [ "$ext" = 'jpg' ]; then
-        [ "$flg_verbose" = true ] && msg_cmd "magick $img_tmp -quality $opt_qual $img_out"
-        magick "$img_tmp" -quality "$opt_qual" "$img_out"
+    cmd_waifu2x=("$bin_waifu2x" -m "$dir_model" -s "$scale" -n "$noise" -i "$img" -o "${img_tmp}")
+    success=0
+    ((quiet)) || msg "$img $bold$blue->$off$white $img_out"
+    if ((verbose)); then
+        msg_cmd "${cmd_waifu2x[@]}"
+        "${cmd_waifu2x[@]}" && success=1
     else
-        [ "$flg_verbose" = true ] && msg_cmd "cp $img_tmp $img_out"
-        cp "$img_tmp" "$img_out"
+        "${cmd_waifu2x[@]}" &>/dev/null && success=1
     fi
-    rm "$img_tmp"
+    if ((success)); then
+        # convert to jpg:
+        if [[ $ext == jpg ]]; then
+            ((verbose)) && msg_cmd magick "$img_tmp" -quality "$quality" "$img_out"
+            magick "$img_tmp" -quality "$quality" "$img_out"
+        else
+            ((verbose)) && msg_cmd cp "$img_tmp" "$img_out"
+            cp "$img_tmp" "$img_out"
+        fi
+    else
+        msg_error "waifu2x error: $img"
+    fi
+    rm -f "$img_tmp"
 done
 
 # vim:ft=bash
diff --git a/bin/usync b/bin/usync
--- a/bin/usync
+++ b/bin/usync
@@ -2,81 +2,76 @@
 ## usync ::
 
 print_help() { cat <<'HELPDOC'
-NAME
-    usync - push/pull changes from remote host
+Usage:
+  usync <command> [option...]
 
-SYNOPSIS
-    usync <command> [option...]
+usync is an rsync wrapper configured by a basic yaml file. usync searches
+the current and parent directories for a file named .usync. The directory
+containing .usync is taken as the base working directory while the contents
+of .usync define a remote rsync host.
 
-DESCRIPTION
-    usync is an rsync wrapper configured by a basic yaml file. usync searches
-    the current and parent directories for a file named .usync. The directory
-    containing .usync is taken as the base working directory while the contents
-    of .usync define a remote rsync host.
+usync forms an rsync command to push/pull sources from the base working
+directory to/from the remote host:
 
-    usync forms an rsync command to push/pull sources from the base working
-    directory to/from the remote host:
+  rsync -aRzz [--delete] [--exclude <pattern>]... <source>... <destination>
 
-        rsync -aRzz [--delete] [--exclude <pattern>]... <source> <destination>
+Command line options override config file options.
 
-    Command line options override config file options.
+Commands:
+  init      create a new .usync file in current directory
+  pull      pull changes from remote rsync host
+  push      push changes to remote rsync host
 
-COMMANDS
-    help    Print help information.
-    init    Create a new .usync file in current directory.
-    pull    Pull changes from remote rsync host.
-    push    Push changes to remote rsync host.
+Options:
+  -c, --config <file>       config file basename (default: .usync)
+  -d, --dir <directory>     remote rsync directory
+  -e, --exclude <pattern>   add exclude pattern, clear patterns if blank
+  -p, --port <port>         remote rsync port number
+  -r, --remote <url>        remote rsync url, may be an ssh alias
+  -s, --source <path>       add to source paths, clear paths if blank
+  -u, --user <user>         emote rsync user
+  -D, --dryrun              perform dry run making no changes
+  -M, --nocolor             disable colored output
+  -N, --nodelete            don't use rsync --delete option
+  -Q, --quiet               print nothing to stdout
+  -V, --verbose             print more verbose information
+  -H, -h, --help            print help text
 
-OPTIONS
-    -c, --config <file>         Set config file basename. (default: .usync)
-    -d, --dir <directory>       Set remote rsync directory.
-    -e, --exclude <pattern>     Add exclude pattern. Clear patterns if blank.
-    -p, --port <port>           Set remote rsync port number.
-    -r, --remote <url>          Set remote rsync url. May be an ssh alias
-    -s, --source <path>         Add source path. Clear paths if blank
-    -u, --user <user>           Set remote rsync user.
-    -D, --dryrun                Perform dry run making no changes.
-    -N, --nodelete              Don't use rsync --delete option.
-    -Q, --quiet                 Don't write anything to stdout.
-    -V, --verbose               Print more verbose information.
-    --nocolor                   Disable colored output.
-    -H, --help                  Print help text.
+Configuration:
+  delete        use rsync --delete option (default: true)
+  exclude       list of rsync --exclude patterns (default: unset)
+  port          remote port (default: unset)
+  remote        remote repo url, may be an ssh alias (required)
+  remote_dir    remote repo directory, must be a full path (required)
+  source        list of sources to pull/push (required)
+  user          remote user (default: unset)
 
-CONFIG
-    remote      Remote repo url. May be an ssh alias. (required)
-    remote_dir  Remote repo directory. Must be a full path. (required)
-    source      List of sources to pull/push. (required)
-    port        Remote port.
-    user        Remote user.
-    delete      Use rsync --delete option
-    exclude     List of patterns to exclude via rsync --exclude option.
-
-ENVIRONMENT
-    NOCOLOR=1   Disable colored output.
-    QUIET=1     Run silently.
-    VERBOSE=1   Run verbosely.
+Environment:
+  NO_COLOR      disable colored output
+  QUIET         run silently
+  VERBOSE       run verbosely
 HELPDOC
 }
 [[ $0 != "${BASH_SOURCE[0]}" ]] && { print_help; return 0 ;}
-[[ $1 =~ ^(-H|--help|help)$ ]] && { print_help; exit ;}
+[[ $1 =~ ^(-H|-h|--help)$ ]] && { print_help; exit ;}
 
 # TODO: allow full path sources?
 # TODO: check if source contains a source?
 # TODO: stat command?
+# TODO: check for leading ~
 
 ## settings ::
-DEBUG="${DEBUG:-0}"
-NOCOLOR="${NOCOLOR:-0}"
-QUIET="${QUIET:-0}"
-VERBOSE="${VERBOSE:-0}"
+debug=0; nocolor=0; quiet=0; verbose=0
 
 ## internal functions/variables ::
 readonly -a args=("$@")
 readonly -a deps=(rsync ssh)
-readonly -a opts=(help init pull push
-    -c: --config: -d: --dir: -e: --exclude: -p: --port: -r: --remote: -s: --source:
-    -u: --user: -N --nodelete -D --dryrun -Q --quiet -V --verbose --debug --nocolor -H --help)
-args_operands=() args_options=()
+readonly -a opts=(
+    init pull push
+    -c: --config: -d: --dir: -e: --exclude: -p: --port: -r: --remote:
+    -s: --source: -u: --user: -D --dryrun -N --nodelete
+    -H -h --help -M --nocolor -Q --quiet -V --verbose)
+args_options=() args_positionals=()
 declare opt_dir opt_port opt_remote opt_user opt_exclude=() opt_source=()
 dir= port= remote= user= exclude=() source=()
 init=0 pull=0 push=0 dryrun=0
@@ -84,58 +79,56 @@ array=() array_new=()
 cmd_rsync=(rsync -aRzz --delete '--info=copy1,del1,name1')
 cmd_rsync=(rsync -aRzz '--info=copy1,del1,name1')
 cmd_sed=(sed -Ee '/\/$/d' -e '/^created /d')
+color_add=
+color_del=
 conf_txt=
 conf=.usync
+delete=1
+exclude_default=(.git /local)
 host="$HOSTNAME"
 remote_dir=
-yaml=
-exclude_default=(.git /local)
 source_default=(./)
-delete=1
+yaml=
 
 # colors:
-blue=$'\e[38;5;12m'
-bold=$'\e[1m'
-green=$'\e[38;5;10m'
-off=$'\e[0m'
-red=$'\e[38;5;9m'
-white=$'\e[38;5;15m'
-yellow=$'\e[38;5;11m'
-clear_colors() { unset blue bold green off red white yellow ;}
-
-# messages:
-msg() { ((QUIET)) || printf "$bold$blue=> $off$white$*$off\n" ;}
-msg2() { ((QUIET)) || printf "$bold$blue > $off$white$*$off\n" ;}
-msg_debug() { ((DEBUG)) && printf "${yellow}D: $off$*\n" >&2 ;}
-msg_error() { printf "$bold${red}E: $off$white$*$off\n" >&2 ;}
-msg_good() { ((QUIET)) || printf "$bold$green=> $off$white$*$off\n" ;}
-msg_plain() { ((QUIET)) || printf "$off$white   $*$off\n" ;}
-msg_warn() { printf "$bold${yellow}W: $off$white$*$off\n" >&2 ;}
-msg_cmd() {
-    ((QUIET)) && return
-    [[ $EUID -eq 0 ]] && printf "$bold$red #" || printf "$bold$blue $"
-    printf "$off$white"; "$cmd_printf" ' %q' "$@"; printf "$off\n"
+black=$'\e[38;5;0m'; blue=$'\e[38;5;12m'; cyan=$'\e[38;5;14m'
+green=$'\e[38;5;10m'; grey=$'\e[38;5;8m'; magenta=$'\e[38;5;13m'
+orange=$'\e[38;5;3m'; red=$'\e[38;5;9m' white=$'\e[38;5;15m'
+yellow=$'\e[38;5;11m'; bold=$'\e[1m'; off=$'\e[0m'
+clear_colors() {
+    unset black blue cyan green grey magenta orange red white yellow bold off
 }
 
-# errors:
-error() { msg_error "$@"; exit 3 ;}
+# messages:
+msg() { printf "$bold$blue=> $off$white$*$off\n" ;}
+msg2() { printf "$bold$blue > $off$white$*$off\n" ;}
+msg_debug() { printf "$yellow$BASH_LINENO$bold: $off$white$*$off\n" >&2 ;}
+msg_error() { printf "$bold${red}E: $off$white$*$off\n" >&2 ;}
+msg_good() { printf "$bold$green=> $off$white$*$off\n" ;}
+msg_plain() { printf "$off$white   $*$off\n" ;}
+msg_warn() { printf "$bold${yellow}W: $off$white$*$off\n" >&2 ;}
+msg_cmd() {
+    local _printf='printf'; [[ -f /usr/bin/printf ]] && _printf='/usr/bin/printf'
+    [[ $EUID -eq 0 ]] && printf "$bold$red #" || printf "$bold$blue $"
+    printf "$off$white"; "$_printf" ' %q' "$@"; printf "$off\n"
+}
 
 # tests:
+check_deps() {
+    local deps_e=()
+    for dep in "${deps[@]}"; do is_cmd "$dep" || deps_e+=("$dep"); done
+    [[ ${#deps_e} -gt 0 ]] && ! ((quiet)) && msg_error "missing deps: ${deps_e[*]}"
+    return ${#deps_e[@]}
+}
 is_cmd() { command -v "$1" &>/dev/null ;}
-is_port() { [[ $1 =~ ^[1-9][0-9]*$ && $1 -lt 65536 ]] ;}
 
-# commands:
-cmd_printf='printf'
-[[ -f '/usr/bin/printf' ]] && cmd_printf='/usr/bin/printf'
-exec_cmd() { ((VERBOSE)) && msg_cmd "$@"; "$@" ;}
-
-# arg parser:
+# parsers:
 parse_args() {
     local a=0 opt= sflgs= sopts= arg="${args[0]}"
     local -a lflgs=() lopts=()
-    bad_opt() { msg_error "unrecognized option: -${arg:2:1}" ;}
-    bad_optarg() { msg_error "option requires an argument: $arg" ;}
-    bad_flg() { msg_error "option does not take argument: ${arg%%=*}" ;}
+    bad_opt() { ((quiet)) || msg_error "unrecognized option: -${arg:2:1}" ;}
+    bad_optarg() { ((quiet)) || msg_error "option requires an argument: $arg" ;}
+    bad_flg() { ((quiet)) || msg_error "option does not take argument: ${arg%%=*}" ;}
     for opt in "${opts[@]}"; do case "$opt" in
         -?) sflgs="$sflgs${opt:1}" ;;
         -?:) sopts="$sopts${opt:1:1}" ;;
@@ -160,13 +153,22 @@ parse_args() {
                 args_options+=("$arg" "${args[((++a))]}")
             else break; fi ;;
     esac; arg="${args[((++a))]}"; done
-    args_operands=("${args[@]:a}")
+    args_positionals=("${args[@]:a}")
+}
+
+parse_arr() {
+    local dup=0
+    arr_new=()
+    for a in "${arr[@]}"; do dup=0
+        [[ -n ${a+x} && -z $a ]] && { arr_new=(); continue ;}
+        for b in "${arr_new[@]}"; do [[ $a == $b ]] && { dup=1; break ;}; done
+        ((dup)) || arr_new+=("$a")
+    done
 }
 
 parse_yaml() {
     local key= arr=() line= a=0
     mapfile -t arr <<<"$yaml"; line="${arr[0]}"
-    bad_yaml() { msg_error "yaml error: $line" ;}
     while [[ -n $line || $a -lt ${#arr[@]} ]]; do
         if [[ $line =~ ^([A-Za-z][A-Za-z0-9_]*):\ *(.*) ]]; then
             key="yaml_${BASH_REMATCH[1]}"; declare -ga "$key"='()'
@@ -176,22 +178,26 @@ parse_yaml() {
         elif [[ $line =~ ^-\ +(.*) && -n $key ]]; then
             declare -ga "$key"+='("${BASH_REMATCH[1]}")'
         elif [[ ! $line =~ ^\ *(#|$) ]]; then
-            bad_yaml; return 3
+            ((quiet)) || msg_error "yaml error: $line"
+            return 3
         fi; line="${arr[((++a))]}"
     done
 }
 
-parse_array() {
-    array_new=()
-    for a in "${array[@]}"; do
-        [[ -n ${a+x} && -z $a ]] && { array_new=(); continue ;}
-        array_new+=("$a")
-    done
-}
+# error, exit, trap:
+error() { msg_error "$*"; exit 3 ;}
+trap_exit() { ((debug)) && msg_debug '[exit]' ;}
+trap_int() { printf '\n'; msg_error '[sigint]'; exit 99 ;}
 
 ## main ::
-trap exit INT
-((NOCOLOR)) || ! [[ -t 1 && -t 2 ]] && clear_colors
+trap trap_int INT
+trap trap_exit EXIT
+
+# set from env:
+[[ -n $DEBUG ]] && debug=1
+[[ -n $NO_COLOR || ! -t 1 || ! -t 2 ]] && { nocolor=1; clear_colors ;}
+[[ -n $QUIET ]] && { quiet=1; verbose=0 ;}
+[[ -n $VERBOSE ]] && { quiet=0; verbose=1 ;}
 
 # parse args:
 parse_args || exit
@@ -209,16 +215,15 @@ while [[ -n "$1" ]]; do case "$1" in
     -u|--user) shift; opt_user="$1" ;;
     -D|--dryrun) dryrun=1 ;;
     -N|--nodelete) delete=0 ;;
-    -Q|--quiet) QUIET=1; VERBOSE=0 ;;
-    -V|--verbose) QUIET=0; VERBOSE=1 ;;
-    --debug) DEBUG=1 ;;
-    --nocolor) clear_colors ;;
-    -H|--help|help) print_help; exit 0 ;;
+    -Q|--quiet) quiet=1; verbose=0 ;;
+    -V|--verbose) quiet=0; verbose=1 ;;
+    -M|--nocolor) nocolor=1; clear_colors ;;
+    -H|-h|--help) print_help; exit 0 ;;
 esac; shift; done
 
-# errors:
-for d in "${deps[@]}"; do is_cmd "$d" || error "missing dependency: $d"; done
-[[ ${#args_operands[@]} -gt 0 ]] && error 'too many arguments'
+# check for errors:
+check_deps || exit
+[[ ${#args_positionals[@]} -gt 0 ]] && error 'too many arguments'
 [[ $((init+push+pull)) -gt 1 ]] && error 'too many commands'
 ((init+push+pull)) || { msg_warn 'no command'; exit 0 ;}
 [[ $conf =~ / ]] && error "config file name is not a basename: $conf"
@@ -239,7 +244,7 @@ if ((init)); then
     if [[ ${#opt_source[@]} -eq 0 ]]; then
         source=("${source_default[@]}")
     else
-        array=("${opt_source[@]}"); parse_array; source=("${array_new[@]}")
+        arr=("${opt_source[@]}"); parse_arr; source=("${arr_new[@]}")
     fi
     if [[ ${#source[@]} -eq 1 ]]; then
         conf_txt+=" ${source[0]}\n"
@@ -249,7 +254,7 @@ if ((init)); then
     if [[ ${#opt_exclude[@]} -eq 0 ]]; then
         exclude=("${exclude_default[@]}")
     else
-        array=("${opt_exclude[@]}"); parse_array; exclude=("${array_new[@]}")
+        arr=("${opt_exclude[@]}"); parse_arr; exclude=("${arr_new[@]}")
     fi
     [[ ${#exclude[@]} -eq 0 ]] && conf_txt+='#'
     ((delete)) && conf_txt+='#delete: true\n' || conf_txt+='delete: false\n'
@@ -264,7 +269,7 @@ if ((init)); then
     conf_txt+='\n# vim:ft=yaml'
     ((dryrun)) || printf "$conf_txt\n" > "$conf"
     msg "usync config created: $conf"
-    ((VERBOSE)) && printf "$conf_txt\n"
+    ((verbose)) && printf "$conf_txt\n"
     ((dryrun)) && msg_warn 'dryrun'
     exit 0
 fi
@@ -281,10 +286,8 @@ port="${opt_port:-$yaml_port}"
 remote="${opt_remote:-$yaml_remote}"
 user="${opt_user:-$yaml_user}"
 [[ ${yaml_delete,,} =~ ^(0|false|no)$ ]] && delete=0
-array=("${yaml_exclude[@]}" "${opt_exclude[@]}"); parse_array
-exclude=("${array_new[@]}")
-array=("${yaml_source[@]}" "${opt_source[@]}"); parse_array
-source=("${array_new[@]}")
+arr=("${yaml_exclude[@]}" "${opt_exclude[@]}"); parse_arr; exclude=("${arr_new[@]}")
+arr=("${yaml_source[@]}" "${opt_source[@]}"); parse_arr; source=("${arr_new[@]}")
 
 # replace leading ~ with $HOME and remove trailing / from dir:
 [[ ${dir:0:1} == '~' ]] && dir="$HOME${dir:1}"
@@ -300,11 +303,6 @@ source=("${array_new[@]}")
 [[ -f /etc/hostname ]] && host="$(cat /etc/hostname)"
 [[ -f /etc/hostname- ]] && host="$(cat /etc/hostname-)"
 [[ $remote =~ ^(|$host|127.0.0.1)$ ]] && remote='localhost'
-
-# debug info:
-msg_debug "delete=$delete dir=$dir port=$port remote=$remote user=$user"
-msg_debug "source=(${source[*]})"
-msg_debug "exclude=(${exclude[*]})"
 
 # set delete option:
 ((delete)) && cmd_rsync+=(--delete)
@@ -329,23 +327,24 @@ fi
 # add excludes to rsync args:
 for e in "${exclude[@]}"; do cmd_rsync+=('--exclude' "$e"); done
 
+# set output colors:
+color_add="$bold$green"; color_del="$bold$red"
 if ((dryrun)); then
-    # add --dry-run to rsync args and set output colors to yellow:
     cmd_rsync+=('--dry-run')
-    cmd_sed+=(-e "s/deleting /$bold$yellow - $off$white/"
-        -e "/ - /! s/^/$bold$yellow + $off$white/")
-else
-    # set output colors to green and red:
-    cmd_sed+=(-e "s/deleting /$bold$red - $off$white/"
-        -e "/ - /! s/^/$bold$green + $off$white/")
+    color_add="$bold$yellow"; color_del="$bold$yellow"
 fi
+cmd_sed+=(-e "/^deleting /! s/^/${color_add} + $off$white/"
+    -e "s/deleting /${color_del} - $off$white/")
 
 # add rsync push/pull args:
 if ((push)); then
     msg "pushing $PWD/ to $remote_dir/"
     if [[ "$remote" == localhost ]]; then
         # create local directory:
-        ((dryrun)) || [[ -d $dir ]] || exec_cmd mkdir -p "$dir"
+        if ! ((dryrun)) && [[ ! -d $dir ]]; then
+            ((verbose)) && msg_cmd mkdir -p "$dir"
+            mkdir -p "$dir"
+        fi
     elif ! ((dryrun)); then
         # create remote directory:
         cmd_rsync+=('--rsync-path' "mkdir -p '$dir' && rsync")
@@ -364,8 +363,9 @@ elif ((pull)); then
 fi
 
 # rsync:
-((VERBOSE)) && msg_cmd "${cmd_rsync[@]}"
-if ((QUIET)); then
+((debug)) && { printf "$yellow${bold}D:"; msg_cmd "${cmd_rsync[@]}"; exit ;}
+((verbose)) && msg_cmd "${cmd_rsync[@]}"
+if ((quiet)); then
     "${cmd_rsync[@]}" 1>/dev/null
 else
     "${cmd_rsync[@]}" | "${cmd_sed[@]}"
