repo-update 2024-11-02 16:15

diff --git a/bin/tirssi b/bin/tirssi
--- a/bin/tirssi
+++ b/bin/tirssi
@@ -1,18 +1,25 @@
-#!/bin/sh
+#!/bin/bash
 
 ## tirssi ::
 # Attach/create irssi tmux session.
 
+## functions ::
+is_cmd() { command -v "$1" &>/dev/null ;}
+
 ## control ::
 cmd='irssi'
+deps=(ssh tmux)
 remote='arch-nas'
 script="$(basename "$0")"
 session="${cmd%% *}"
-settings='set status off; set pane-border-status off'
+settings=('status off' 'pane-border-status off')
 socket="$session"
 
 ## main ::
 set -e
+
+# dependency error:
+for dep in "${deps[@]}"; do is_cmd "$dep" || error "not found: $dep"; done
 
 # ssh into remote and run script there:
 if [ -n "$remote" ] && [ "$remote" != 'localhost' ] &&
